### ISSUE TITLE
Investigate edge cases to avoid deadlock in threads

### ISSUE THREAD

**Issue by ljwoods2** [Becksteinlab/imdreader#3]
- How does gromacs handle termination and kill signals w.r.t. IMD? Will it always send a complete frame, or can it stop mid-postion data or between energies and positions for example?

**Comment by ljwoods2** [comment]
Potential solution is to just parse the stream inside a `try:` block and include a `finally:` that prevents the IMDReader thread from getting deadlocked

**Comment by HeydenLabASU** [comment]
In terms of trajectory output (to a file), gromacs always writes complete frames as far as I know. Everything else would be detrimental. The same behavior would be great for IMD V3 but I do not know how this is handled in IMD V2

**Comment by ljwoods2** [comment]
#7 Fixed here using `read_into_buf`
